version: '3.1'

services:
  api:
    container_name: defeito-motor-eletrico
    image: defeito-motor-eletrico:0.1
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      TZ: "America/Sao_Paulo"
      YGOR_DB: ${YGOR_DB}
      YGOR_USER: ${YGOR_USER}
      YGOR_PASSWORD: ${YGOR_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime
