spring:
  application:
    name: defeito-motor-eletrico
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${YGOR_DB:jdbc:postgresql://93.188.161.151:5432/TCC}
    username: ${YGOR_USER_DB:ygor_adm}
    password: ${YGOR_PASSWORD_DB:1234}
  main:
    allow-circular-references: true
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8085
  servlet:
    context-path: /defeito-motor-eletrico

#springdoc:
#  api-docs:
#    path: /api-docs

acesso-externo:
  uri: http://gateway-server:5555/siisp-acesso/v1/usuarios/cpf/

security:
  jwt:
    expiracao: 86400
    chave-assinatura: b25lLWZvci1hbGw=

mqtt:
  username: ygor_admin
  password: TESTE_1234
  host-url:
    - tcp://93:188:161151:1883
  client-id: mqttId2
  default-topic: topic
  connection-timeout: 3000
  subscription-topic:
    - $share/group1/hello
    - $share/group1/hello1