spring:
  application:
    name: defeito-motor-eletrico
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${YGOR_DB}
    username: ${YGOR_USER_DB}
    password: ${YGOR_PASSWORD_DB}
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8080
  servlet:
    context-path: /defeito-motor-eletrico

acesso-externo:
  uri: http://gateway-server:5555/siisp-acesso/v1/usuarios/cpf/